### ISSUE TITLE
Script cannot be executed using defined shebang

### ISSUE THREAD

**Issue by achou11** [ABGEO/httpinfo#1]
The script currently uses `sh` via the shebang (`#!/bin/env sh`) but depends on language features that are not `sh` compatible (see output in [shellcheck](https://www.shellcheck.net/)), which seems to cause errors. Example of execution after installation:

```
./httpinfo.sh: 11: Syntax error: "(" unexpected
```

A couple of potential ways to fix:

- Change the shebang to use `bash` (I did this and it worked)
- Update the script to be POSIX compliant

**Comment by ABGEO** [comment]
@achou11 thanks for your contribution!

I developed this script for Bash but missed the shebang. In my development machine, `sh` is a symlink to `bash`.

I will release a new version ASAP.

**Comment by ABGEO** [comment]
Fixed in this [release](https://github.com/ABGEO/httpinfo/releases/tag/v1.0.1).

Thanks @achou11!
